(base) root@ubuntu:/home/wen/LDI/Experiments/scripts/PoC/cvxopt# python diag_193.py 
Gonna set new name [CHOLMOD FACTOR YYYYYYYYYYYYY].
Set result: [CHOLMOD FACTOR YYYYYYYYYYYYY].
5.505331535932363
*** buffer overflow detected ***: python terminated
Aborted (core dumped)
(base) root@ubuntu:/home/wen/LDI/Experiments/scripts/PoC/cvxopt# ll /var/crash/
total 80124
drwxrwsrwt  2 root whoopsie     4096 Sep 17 16:00  ./
drwxr-xr-x 14 root root         4096 Aug  6  2020  ../
-rw-------  1 root whoopsie 82747392 Sep 17 16:00 '!usr!lib!anaconda3!bin!python3.7.2008.1631919611.6'
(base) root@ubuntu:/home/wen/LDI/Experiments/scripts/PoC/cvxopt# gdb python /var/crash/\!usr\!lib\!anaconda3\!bin\!python3.7.2008.1631919611.6 
GNU gdb (Ubuntu 8.1.1-0ubuntu1) 8.1.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python...done.

warning: core file may not match specified executable file.
[New LWP 2008]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `python diag_193.py'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007fbed628a921 in __GI_abort () at abort.c:79
#2  0x00007fbed62d3967 in __libc_message (action=action@entry=(do_abort | do_backtrace), fmt=fmt@entry=0x7fbed64008fb "*** %s ***: %s terminated\n")
    at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007fbed637eb8f in __GI___fortify_fail_abort (need_backtrace=need_backtrace@entry=true, msg=msg@entry=0x7fbed6400878 "buffer overflow detected")
    at fortify_fail.c:33
#4  0x00007fbed637ebb1 in __GI___fortify_fail (msg=msg@entry=0x7fbed6400878 "buffer overflow detected") at fortify_fail.c:44
#5  0x00007fbed637c8a0 in __GI___chk_fail () at chk_fail.c:28
#6  0x00007fbed4ac5201 in memset (__len=255, __ch=2, __dest=0x7ffe27f87b86) at /usr/include/x86_64-linux-gnu/bits/string_fortified.h:71
#7  Capsule_New (self=<optimized out>, args=<optimized out>) at Demo.c:36
#8  0x0000563517ee3884 in _PyMethodDef_RawFastCallKeywords () at /tmp/build/80754af9/python_1598874792229/work/Objects/call.c:697
#9  0x0000563517ee3a31 in _PyCFunction_FastCallKeywords (func=0x7fbed4cce370, args=<optimized out>, nargs=<optimized out>, kwnames=<optimized out>)
    at /tmp/build/80754af9/python_1598874792229/work/Objects/call.c:732
#10 0x0000563517f4f795 in call_function (kwnames=0x0, oparg=1, pp_stack=<synthetic pointer>) at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:4568
#11 _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:3124
#12 0x0000563517e92829 in _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:3930
#13 0x0000563517e93714 in PyEval_EvalCodeEx () at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:3959
#14 0x0000563517e9373c in PyEval_EvalCode (co=<optimized out>, globals=<optimized out>, locals=<optimized out>)
    at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:524
#15 0x0000563517faaf14 in run_mod () at /tmp/build/80754af9/python_1598874792229/work/Python/pythonrun.c:1035
#16 0x0000563517fb5331 in PyRun_FileExFlags () at /tmp/build/80754af9/python_1598874792229/work/Python/pythonrun.c:988
#17 0x0000563517fb5523 in PyRun_SimpleFileExFlags () at /tmp/build/80754af9/python_1598874792229/work/Python/pythonrun.c:429
#18 0x0000563517fb6655 in pymain_run_file (p_cf=0x7ffe27f87f70, filename=0x5635195216b0 L"diag_193.py", fp=0x563519568e70)
    at /tmp/build/80754af9/python_1598874792229/work/Modules/main.c:462
#19 pymain_run_filename (cf=0x7ffe27f87f70, pymain=0x7ffe27f88080) at /tmp/build/80754af9/python_1598874792229/work/Modules/main.c:1652
#20 pymain_run_python (pymain=0x7ffe27f88080) at /tmp/build/80754af9/python_1598874792229/work/Modules/main.c:2913
#21 pymain_main () at /tmp/build/80754af9/python_1598874792229/work/Modules/main.c:3460
#22 0x0000563517fb677c in _Py_UnixMain () at /tmp/build/80754af9/python_1598874792229/work/Modules/main.c:3495
#23 0x00007fbed626bbf7 in __libc_start_main (main=0x563517e73c90 <main>, argc=2, argv=0x7ffe27f881d8, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7ffe27f881c8) at ../csu/libc-start.c:310
#24 0x0000563517f5aff0 in _start () at ../sysdeps/x86_64/elf/start.S:103
(gdb) 