(base) root@ubuntu:/home/wen/LDI/Experiments/scripts/PoC/pyo# python restart_222.py 

WxPython is not found for the current python version.
Pyo will use a minimal GUI toolkit written with Tkinter (if available).
This toolkit has limited functionnalities and is no more
maintained or updated. If you want to use all of pyo's
GUI features, you should install WxPython, available here:
http://www.wxpython.org/

XDG_RUNTIME_DIR (/run/user/1000) is not owned by us (uid 0), but by uid 1000! (This could e g happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM sysdefault
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM sysdefault
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.front
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround40
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround41
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround50
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround51
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
XDG_RUNTIME_DIR (/run/user/1000) is not owned by us (uid 0), but by uid 1000! (This could e g happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

XDG_RUNTIME_DIR (/run/user/1000) is not owned by us (uid 0), but by uid 1000! (This could e g happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM dmix
Segmentation fault (core dumped)
(base) root@ubuntu:/home/wen/LDI/Experiments/scripts/PoC/pyo# ll /var/crash/
total 34176
drwxrwsrwt  2 root whoopsie     4096 Sep 17 15:42  ./
drwxr-xr-x 14 root root         4096 Aug  6  2020  ../
-rw-------  1 root whoopsie 26382336 Sep 17 15:42 '!usr!lib!anaconda3!bin!python3.7.4278.1631946196.11'
(base) root@ubuntu:/home/wen/LDI/Experiments/scripts/PoC/pyo# gdb python /var/crash/\!usr\!lib\!anaconda3\!bin\!python3.7.4278.1631946196.11 
GNU gdb (Ubuntu 8.1.1-0ubuntu1) 8.1.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python...done.

warning: core file may not match specified executable file.
[New LWP 4278]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `python restart_222.py'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f52d4fe120e in Server_pa_init ()
   from /usr/lib/anaconda3/lib/python3.7/site-packages/pyo-1.0.3-py3.7-linux-x86_64.egg/pyo/_pyo.cpython-37m-x86_64-linux-gnu.so
(gdb) bt
#0  0x00007f52d4fe120e in Server_pa_init ()
   from /usr/lib/anaconda3/lib/python3.7/site-packages/pyo-1.0.3-py3.7-linux-x86_64.egg/pyo/_pyo.cpython-37m-x86_64-linux-gnu.so
#1  0x00007f52d4fca828 in Server_boot ()
   from /usr/lib/anaconda3/lib/python3.7/site-packages/pyo-1.0.3-py3.7-linux-x86_64.egg/pyo/_pyo.cpython-37m-x86_64-linux-gnu.so
#2  0x000056281358572d in _PyMethodDef_RawFastCallKeywords () at /tmp/build/80754af9/python_1598874792229/work/Objects/call.c:647
#3  0x000056281358c7af in _PyMethodDescr_FastCallKeywords () at /tmp/build/80754af9/python_1598874792229/work/Objects/descrobject.c:288
#4  0x00005628135f1c7c in call_function (kwnames=0x0, oparg=2, pp_stack=<synthetic pointer>) at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:4593
#5  _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:3110
#6  0x0000562813534829 in _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:3930
#7  0x00005628135850a5 in _PyFunction_FastCallKeywords () at /tmp/build/80754af9/python_1598874792229/work/Objects/call.c:433
#8  0x00005628135ed740 in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>)
    at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:4616
#9  _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:3110
#10 0x0000562813534829 in _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:3930
#11 0x0000562813535714 in PyEval_EvalCodeEx () at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:3959
#12 0x000056281353573c in PyEval_EvalCode (co=<optimized out>, globals=<optimized out>, locals=<optimized out>)
    at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:524
#13 0x000056281364cf14 in run_mod () at /tmp/build/80754af9/python_1598874792229/work/Python/pythonrun.c:1035
#14 0x0000562813657331 in PyRun_FileExFlags () at /tmp/build/80754af9/python_1598874792229/work/Python/pythonrun.c:988
#15 0x0000562813657523 in PyRun_SimpleFileExFlags () at /tmp/build/80754af9/python_1598874792229/work/Python/pythonrun.c:429
#16 0x0000562813658655 in pymain_run_file (p_cf=0x7fff7f87c510, filename=0x5628147ef6c0 L"restart_222.py", fp=0x562814836f40)
    at /tmp/build/80754af9/python_1598874792229/work/Modules/main.c:462
#17 pymain_run_filename (cf=0x7fff7f87c510, pymain=0x7fff7f87c620) at /tmp/build/80754af9/python_1598874792229/work/Modules/main.c:1652
#18 pymain_run_python (pymain=0x7fff7f87c620) at /tmp/build/80754af9/python_1598874792229/work/Modules/main.c:2913
#19 pymain_main () at /tmp/build/80754af9/python_1598874792229/work/Modules/main.c:3460
#20 0x000056281365877c in _Py_UnixMain () at /tmp/build/80754af9/python_1598874792229/work/Modules/main.c:3495
#21 0x00007f52d67d9bf7 in __libc_start_main (main=0x562813515c90 <main>, argc=2, argv=0x7fff7f87c778, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fff7f87c768) at ../csu/libc-start.c:310
#22 0x00005628135fcff0 in _start () at ../sysdeps/x86_64/elf/start.S:103
(gdb) 
