(base) root@ubuntu:/home/wen/LDI/Experiments/scripts/PoC/japronto# 
(base) root@ubuntu:/home/wen/LDI/Experiments/scripts/PoC/japronto# 
(base) root@ubuntu:/home/wen/LDI/Experiments/scripts/PoC/japronto# killall python             
Termination request received
(base) root@ubuntu:/home/wen/LDI/Experiments/scripts/PoC/japronto# python feed_183_server.py &
[2] 1990
[1]   Done                    python feed_183_server.py
(base) root@ubuntu:/home/wen/LDI/Experiments/scripts/PoC/japronto# Accepting connections on http://0.0.0.0:9999

(base) root@ubuntu:/home/wen/LDI/Experiments/scripts/PoC/japronto# python feed_183_client.py  
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b738fdd0>
transport: <TCPTransport closed=False reading=False 0x5622b72c2080>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
incomplete_body
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b7391a00>
transport: <TCPTransport closed=False reading=False 0x5622b734cd50>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b7393630>
transport: <TCPTransport closed=False reading=False 0x5622b72f6500>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b7395260>
transport: <TCPTransport closed=False reading=False 0x5622b72de730>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b7396e90>
transport: <TCPTransport closed=False reading=False 0x5622b728a9a0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b7398ac0>
transport: <TCPTransport closed=False reading=False 0x5622b71e1240>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b739a6f0>
transport: <TCPTransport closed=False reading=False 0x5622b71f57f0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b739c320>
transport: <TCPTransport closed=False reading=False 0x5622b72ed3f0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b739df50>
transport: <TCPTransport closed=False reading=False 0x5622b72eb410>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b739fb80>
transport: <TCPTransport closed=False reading=False 0x5622b72eb7d0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73a17b0>
transport: <TCPTransport closed=False reading=False 0x5622b72ebb90>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73a33e0>
transport: <TCPTransport closed=False reading=False 0x5622b73a5030>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73a52d0>
transport: <TCPTransport closed=False reading=False 0x5622b73a6f20>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73a71c0>
transport: <TCPTransport closed=False reading=False 0x5622b73a8e10>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73a90b0>
transport: <TCPTransport closed=False reading=False 0x5622b73aad00>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73aafa0>
transport: <TCPTransport closed=False reading=False 0x5622b73acbf0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73ace90>
transport: <TCPTransport closed=False reading=False 0x5622b73aeae0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73aed80>
transport: <TCPTransport closed=False reading=False 0x5622b73b09d0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73b0c70>
transport: <TCPTransport closed=False reading=False 0x5622b73b28c0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73b3370>
transport: <TCPTransport closed=False reading=False 0x5622b73b4fc0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73b5260>
transport: <TCPTransport closed=False reading=False 0x5622b73b6eb0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73b7150>
transport: <TCPTransport closed=False reading=False 0x5622b73b8da0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73b94a0>
transport: <TCPTransport closed=False reading=False 0x5622b73bb0f0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73bb390>
transport: <TCPTransport closed=False reading=False 0x5622b73bcfe0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73bd280>
transport: <TCPTransport closed=False reading=False 0x5622b73beed0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73bf170>
transport: <TCPTransport closed=False reading=False 0x5622b73c0dc0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73c1060>
transport: <TCPTransport closed=False reading=False 0x5622b73c2cb0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73c2f50>
transport: <TCPTransport closed=False reading=False 0x5622b73c4ba0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73c4e40>
transport: <TCPTransport closed=False reading=False 0x5622b73c6a90>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73c6d30>
transport: <TCPTransport closed=False reading=False 0x5622b73c8980>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
  File "feed_183_client.py", line 20, in <module>
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73c8c20>
transport: <TCPTransport closed=False reading=False 0x5622b73ca870>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
    loop.run_until_complete(fetch_all(loop))
  File "/usr/lib/anaconda3/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73cab10>
transport: <TCPTransport closed=False reading=False 0x5622b73cc760>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
    return future.result()
  File "feed_183_client.py", line 16, in fetch_all
    results = await asyncio.gather(*[fetch(session, i) for i in range(NPARALLEL)])
  File "feed_183_client.py", line 9, in fetch
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73cca00>
transport: <TCPTransport closed=False reading=False 0x5622b73ce650>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
    async with session.post("http://127.0.0.1:9999/poc", data=f"POC testing message: session {i}") as response:
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/aiohttp/client.py", line 1117, in __aenter__
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73ce8f0>
transport: <TCPTransport closed=False reading=False 0x5622b73d0540>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73d07e0>
transport: <TCPTransport closed=False reading=False 0x5622b73d2430>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
    self._resp = await self._coro
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/aiohttp/client.py", line 544, in _request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73d26d0>
transport: <TCPTransport closed=False reading=False 0x5622b73d4320>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
    await resp.start(conn)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 890, in start
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73d45c0>
transport: <TCPTransport closed=False reading=False 0x5622b73d6210>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
    message, payload = await self._protocol.read()  # type: ignore
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/aiohttp/streams.py", line 604, in read
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73d64b0>
transport: <TCPTransport closed=False reading=False 0x5622b73d8100>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73d83a0>
transport: <TCPTransport closed=False reading=False 0x5622b73d9ff0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73da290>
transport: <TCPTransport closed=False reading=False 0x5622b73dbee0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73dc180>
transport: <TCPTransport closed=False reading=False 0x5622b73dddd0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73de070>
transport: <TCPTransport closed=False reading=False 0x5622b73dfcc0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73dff60>
transport: <TCPTransport closed=False reading=False 0x5622b73e1bb0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73e2700>
transport: <TCPTransport closed=False reading=False 0x5622b73b9060>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73e4330>
transport: <TCPTransport closed=False reading=False 0x5622b73e5f80>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73e6220>
transport: <TCPTransport closed=False reading=False 0x5622b73e7e70>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73e8110>
transport: <TCPTransport closed=False reading=False 0x5622b73e9d60>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73ea410>
transport: <TCPTransport closed=False reading=False 0x5622b73ec060>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73ec300>
transport: <TCPTransport closed=False reading=False 0x5622b73edf50>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73ee1f0>
transport: <TCPTransport closed=False reading=False 0x5622b73efe40>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73f00e0>
transport: <TCPTransport closed=False reading=False 0x5622b73f1d30>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73f20d0>
transport: <TCPTransport closed=False reading=False 0x5622b73f3d20>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73f40c0>
transport: <TCPTransport closed=False reading=False 0x5622b73f5d10>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73f60b0>
transport: <TCPTransport closed=False reading=False 0x5622b73f7d00>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73f80a0>
transport: <TCPTransport closed=False reading=False 0x5622b73f9cf0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73fa090>
transport: <TCPTransport closed=False reading=False 0x5622b73fbce0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73fc080>
transport: <TCPTransport closed=False reading=False 0x5622b73fdcd0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b73fe070>
transport: <TCPTransport closed=False reading=False 0x5622b73ffcc0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b7400060>
transport: <TCPTransport closed=False reading=False 0x5622b7401cb0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b7402050>
transport: <TCPTransport closed=False reading=False 0x5622b7403ca0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b7404040>
transport: <TCPTransport closed=False reading=False 0x5622b7405c90>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b7406030>
transport: <TCPTransport closed=False reading=False 0x5622b7407c80>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b7408020>
transport: <TCPTransport closed=False reading=False 0x5622b7409c70>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b740a010>
transport: <TCPTransport closed=False reading=False 0x5622b740bc60>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b740c000>
transport: <TCPTransport closed=False reading=False 0x5622b740dc50>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b740dff0>
transport: <TCPTransport closed=False reading=False 0x5622b740fc40>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b740ffe0>
transport: <TCPTransport closed=False reading=False 0x5622b7411c30>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b7411fd0>
transport: <TCPTransport closed=False reading=False 0x5622b7413c20>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b7413fc0>
transport: <TCPTransport closed=False reading=False 0x5622b7415c10>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b7415fb0>
transport: <TCPTransport closed=False reading=False 0x5622b7417c00>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b7417fa0>
transport: <TCPTransport closed=False reading=False 0x5622b7419bf0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b7419f90>
transport: <TCPTransport closed=False reading=False 0x5622b741bbe0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b741bf80>
transport: <TCPTransport closed=False reading=False 0x5622b741dbd0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b741df70>
transport: <TCPTransport closed=False reading=False 0x5622b741fbc0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b741ff60>
transport: <TCPTransport closed=False reading=False 0x5622b7421bb0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b7421f50>
transport: <TCPTransport closed=False reading=False 0x5622b7423ba0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b7423f40>
transport: <TCPTransport closed=False reading=False 0x5622b7425b90>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b7427f40>
transport: <TCPTransport closed=False reading=False 0x5622b73b2b80>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b7429b70>
transport: <TCPTransport closed=False reading=False 0x5622b73b2f40>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b742b7a0>
transport: <TCPTransport closed=False reading=False 0x5622b742d3f0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b742d790>
transport: <TCPTransport closed=False reading=False 0x5622b742f3e0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b742f780>
transport: <TCPTransport closed=False reading=False 0x5622b74313d0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b7431770>
transport: <TCPTransport closed=False reading=False 0x5622b74333c0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b7433760>
transport: <TCPTransport closed=False reading=False 0x5622b74353b0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b7435750>
transport: <TCPTransport closed=False reading=False 0x5622b74373a0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b7437740>
transport: <TCPTransport closed=False reading=False 0x5622b7439390>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b743a950>
transport: <TCPTransport closed=False reading=False 0x5622b73e1e70>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b743c580>
transport: <TCPTransport closed=False reading=False 0x5622b73e2230>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b743e1b0>
transport: <TCPTransport closed=False reading=False 0x5622b743fe00>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b74400a0>
transport: <TCPTransport closed=False reading=False 0x5622b7441cf0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b7442090>
transport: <TCPTransport closed=False reading=False 0x5622b7443ce0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b7444080>
transport: <TCPTransport closed=False reading=False 0x5622b7445cd0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b7446070>
transport: <TCPTransport closed=False reading=False 0x5622b7447cc0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b7448060>
transport: <TCPTransport closed=False reading=False 0x5622b7449cb0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b744a050>
transport: <TCPTransport closed=False reading=False 0x5622b744bca0>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b744c040>
transport: <TCPTransport closed=False reading=False 0x5622b744dc90>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b744e030>
transport: <TCPTransport closed=False reading=False 0x5622b744fc80>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b7450020>
transport: <TCPTransport closed=False reading=False 0x5622b7451c70>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b7452010>
transport: <TCPTransport closed=False reading=False 0x5622b7453c60>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
Traceback (most recent call last):
  File "feed_183_server.py", line 7, in RP
    return r.Response(text=body)
TypeError: bad argument type for built-in operation
Fatal error on transport TCPTransport
protocol: <cprotocol.Protocol object at 0x5622b7454000>
transport: <TCPTransport closed=False reading=False 0x5622b7455c50>
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 104, in error_handler
    return self.default_error_handler(request, exception)
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/japronto-0.1.2-py3.7-linux-x86_64.egg/japronto/app/__init__.py", line 86, in default_error_handler
    text=tb if self._debug else 'Internal Server Error')
RuntimeError: Request.Response can only be called once per request
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
incomplete_body
