(base) root@ubuntu:/home/wen/LDI/Experiments/scripts/PoC/cvxopt# python getfactor_193.py 
Gonna set new name [CHOLMOD FACTOR YYYYYYYYYYYYY].
Set result: [CHOLMOD FACTOR YYYYYYYYYYYYY].
[ 3.16e+00     0         0         0    ]
[ 9.49e-01  2.02e+00     0         0    ]
[    0         0      2.24e+00     0    ]
[    0         0     -8.94e-01  1.10e+00]

*** buffer overflow detected ***: python terminated
Aborted (core dumped)
(base) root@ubuntu:/home/wen/LDI/Experiments/scripts/PoC/cvxopt# ll /var/crash
total 80124
drwxrwsrwt  2 root whoopsie     4096 Sep 17 16:01  ./
drwxr-xr-x 14 root root         4096 Aug  6  2020  ../
-rw-------  1 root whoopsie 82747392 Sep 17 16:01 '!usr!lib!anaconda3!bin!python3.7.2017.1631919661.6'
(base) root@ubuntu:/home/wen/LDI/Experiments/scripts/PoC/cvxopt# gdb python /var/crash/\!usr\!lib\!anaconda3\!bin\!python3.7.2017.1631919661.6 
GNU gdb (Ubuntu 8.1.1-0ubuntu1) 8.1.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python...done.

warning: core file may not match specified executable file.
[New LWP 2017]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `python getfactor_193.py'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f38e8fc4921 in __GI_abort () at abort.c:79
#2  0x00007f38e900d967 in __libc_message (action=action@entry=(do_abort | do_backtrace), fmt=fmt@entry=0x7f38e913a8fb "*** %s ***: %s terminated\n")
    at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007f38e90b8b8f in __GI___fortify_fail_abort (need_backtrace=need_backtrace@entry=true, msg=msg@entry=0x7f38e913a878 "buffer overflow detected")
    at fortify_fail.c:33
#4  0x00007f38e90b8bb1 in __GI___fortify_fail (msg=msg@entry=0x7f38e913a878 "buffer overflow detected") at fortify_fail.c:44
#5  0x00007f38e90b68a0 in __GI___chk_fail () at chk_fail.c:28
#6  0x00007f38e77ff201 in memset (__len=255, __ch=2, __dest=0x7ffe342c3876) at /usr/include/x86_64-linux-gnu/bits/string_fortified.h:71
#7  Capsule_New (self=<optimized out>, args=<optimized out>) at Demo.c:36
#8  0x0000563166c38884 in _PyMethodDef_RawFastCallKeywords () at /tmp/build/80754af9/python_1598874792229/work/Objects/call.c:697
#9  0x0000563166c38a31 in _PyCFunction_FastCallKeywords (func=0x7f38e7a07500, args=<optimized out>, nargs=<optimized out>, kwnames=<optimized out>)
    at /tmp/build/80754af9/python_1598874792229/work/Objects/call.c:732
#10 0x0000563166ca4795 in call_function (kwnames=0x0, oparg=1, pp_stack=<synthetic pointer>) at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:4568
#11 _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:3124
#12 0x0000563166be7829 in _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:3930
#13 0x0000563166be8714 in PyEval_EvalCodeEx () at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:3959
#14 0x0000563166be873c in PyEval_EvalCode (co=<optimized out>, globals=<optimized out>, locals=<optimized out>)
    at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:524
#15 0x0000563166cfff14 in run_mod () at /tmp/build/80754af9/python_1598874792229/work/Python/pythonrun.c:1035
#16 0x0000563166d0a331 in PyRun_FileExFlags () at /tmp/build/80754af9/python_1598874792229/work/Python/pythonrun.c:988
#17 0x0000563166d0a523 in PyRun_SimpleFileExFlags () at /tmp/build/80754af9/python_1598874792229/work/Python/pythonrun.c:429
#18 0x0000563166d0b655 in pymain_run_file (p_cf=0x7ffe342c3c60, filename=0x56316877b6c0 L"getfactor_193.py", fp=0x5631687c2f40)
    at /tmp/build/80754af9/python_1598874792229/work/Modules/main.c:462
#19 pymain_run_filename (cf=0x7ffe342c3c60, pymain=0x7ffe342c3d70) at /tmp/build/80754af9/python_1598874792229/work/Modules/main.c:1652
#20 pymain_run_python (pymain=0x7ffe342c3d70) at /tmp/build/80754af9/python_1598874792229/work/Modules/main.c:2913
#21 pymain_main () at /tmp/build/80754af9/python_1598874792229/work/Modules/main.c:3460
#22 0x0000563166d0b77c in _Py_UnixMain () at /tmp/build/80754af9/python_1598874792229/work/Modules/main.c:3495
#23 0x00007f38e8fa5bf7 in __libc_start_main (main=0x563166bc8c90 <main>, argc=2, argv=0x7ffe342c3ec8, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7ffe342c3eb8) at ../csu/libc-start.c:310
#24 0x0000563166cafff0 in _start () at ../sysdeps/x86_64/elf/start.S:103
(gdb) 