(base) root@ubuntu:/home/wen/LDI/Experiments/numpy/numpy/f2py/tests# pytest array_attr_19000.py 
======================================================================= test session starts =======================================================================
platform linux -- Python 3.7.9, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
rootdir: /home/wen/LDI/Experiments/numpy, configfile: pytest.ini
plugins: hypothesis-6.8.3
collected 18 items                                                                                                                                                
Collect case count:  18

array_attr_19000.py .Fatal Python error: Aborted

Current thread 0x00007ff75f5d8740 (most recent call first):
  File "/home/wen/LDI/Experiments/numpy/numpy/f2py/tests/array_attr_19000.py", line 204 in __init__
  File "/home/wen/LDI/Experiments/numpy/numpy/f2py/tests/array_attr_19000.py", line 315 in <lambda>
  File "/home/wen/LDI/Experiments/numpy/numpy/f2py/tests/array_attr_19000.py", line 319 in test_cache_hidden
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/_pytest/python.py", line 184 in pytest_pyfunc_call
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/pluggy/manager.py", line 87 in <lambda>
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/_pytest/python.py", line 1627 in runtest
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/_pytest/runner.py", line 166 in pytest_runtest_call
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/pluggy/manager.py", line 87 in <lambda>
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/_pytest/runner.py", line 259 in <lambda>
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/_pytest/runner.py", line 313 in from_call
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/_pytest/runner.py", line 259 in call_runtest_hook
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/_pytest/runner.py", line 219 in call_and_report
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/_pytest/runner.py", line 130 in runtestprotocol
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/_pytest/runner.py", line 110 in pytest_runtest_protocol
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/pluggy/manager.py", line 87 in <lambda>
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/_pytest/main.py", line 348 in pytest_runtestloop
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/pluggy/manager.py", line 87 in <lambda>
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/_pytest/main.py", line 313 in _main
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/_pytest/main.py", line 257 in wrap_session
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/_pytest/main.py", line 306 in pytest_cmdline_main
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/pluggy/manager.py", line 87 in <lambda>
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/usr/lib/anaconda3/lib/python3.7/site-packages/_pytest/config/__init__.py", line 165 in main
  File "/usr/lib/anaconda3/bin/pytest", line 11 in <module>
Aborted